baseurl: ""
full_url: "http://www.rundeck.org"
rd_version: "3.3.6-20201111"
rd_short_version: "3.3.6"

rd_war_name: "rundeck-3.3.6-20201111.war"
rd_war_sha: "aeb9d8f0603d98cca8c1a7bdb2878af9a76427fc"
rd_war_url: "https://download.rundeck.org/war/rundeck-3.3.6-20201111.war"
rd_war_size: "175217944"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.3.6.20201111-1_all.deb"
rd_deb_url: "https://download.rundeck.org/deb/rundeck_3.3.6.20201111-1_all.deb"
rd_deb_sha: "b40d34261dc6890b680645ef7f208132b776c71c"
rd_deb_size: "179889496"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.3.6"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.3.6"
rd_releasenotes: "https://docs.rundeck.com/docs/history/3_3_x/version-3.3.6.html"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
