baseurl: ""
full_url: "http://www.rundeck.org"
rd_version: "3.0.12.20190114"

rd_war_name: "rundeck-3.0.12-20190114.war"
rd_war_sha: "66991520ed37a4682b62cf307081de13dcea6c4d"
rd_war_url: "https://download.rundeck.org/war/rundeck-3.0.9-20181127.war"
rd_war_size: "140346391"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.0.12.20190114-1.201901142226_all.deb"
rd_deb_url: "https://download.rundeck.org/deb/rundeck_3.0.12.20190114-1.201901142226_all.deb"
rd_deb_sha: "0dd75421d87b10f20352b841b74121d4adb52f4e"
rd_deb_size: "152209302"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.0.12"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.0.12"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v3.0.12/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
