baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.11.0"
rd_jar_name: "rundeck-launcher-2.11.0.jar"
rd_jar_sha: "c99fed5086a7289a123092a4089b2f2f36f8e138"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.0.jar"
rd_jar_size: "102311356"
rd_deb_name: "rundeck_2.11.0-1-GA_all.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck_2.11.0-1-GA_all.deb"
rd_deb_sha: "4354401b42bb140687816adc4418ea010aab21ae"
rd_deb_size: "115121274"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.11.0"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.11.0"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.11.0/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
