baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.11.5"
rd_jar_name: "rundeck-launcher-2.11.5.jar"
rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
rd_jar_size: "102496072"
rd_deb_name: "rundeck_2.11.5-1-GA_all.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck_2.11.5-1-GA_all.deb"
rd_deb_sha: "002037314382f8f7d0052ef4d4c961ae76e0ac6d"
rd_deb_size: "115218778"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.11.5"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.11.5"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.11.5/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
