baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.11.2"
rd_jar_name: "rundeck-launcher-2.11.2.jar"
rd_jar_sha: "87f6d85ea46f00ef3afab2ee250934d8a53845d8"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.2.jar"
rd_jar_size: "102318699"
rd_deb_name: "rundeck_2.11.2-1-GA_all.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck_2.11.2-1-GA_all.deb"
rd_deb_sha: "ec109ecf161f3fcf3ba4693b6b65db5b735c7606"
rd_deb_size: "115135264"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.11.2"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.11.2"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.11.2/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
