baseurl: ""
full_url: "http://www.rundeck.org"
rd_version: "3.0.11.20181221"

rd_war_name: "rundeck-3.0.11-20181221.war"
rd_war_sha: "449f3e790b5b350eb815c452380f441406681a8f"
rd_war_url: "https://download.rundeck.org/war/rundeck-3.0.9-20181127.war"
rd_war_size: "140346354"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.0.11.20181221-1.201812212337_all.deb"
rd_deb_url: "https://download.rundeck.org/deb/rundeck_3.0.11.20181221-1.201812212337_all.deb"
rd_deb_sha: "7deef82f94d3868a786ffa6b7f60ce08b13759ae"
rd_deb_size: "152204974"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.0.11"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.0.11"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v3.0.11/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
