baseurl: ""
full_url: "http://www.rundeck.org"
rd_version: "3.1.3-20191204"
rd_short_version: "3.1.3"

rd_war_name: "rundeck-3.1.3-20191204.war"
rd_war_sha: "7bc2c8a5e0c436d97f062c73c23fb744fb0de358"
rd_war_url: "https://download.rundeck.org/war/rundeck-3.1.3-20191204.war"
rd_war_size: "158949640"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.1.3.20191204-1_all.deb"
rd_deb_url: "https://download.rundeck.org/deb/rundeck_3.1.3.20191204-1_all.deb"
rd_deb_sha: "dc542358d069b2a1221166694e88f01993dff765"
rd_deb_size: "172242846"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.1.3"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.1.3"
rd_releasenotes: "https://docs.rundeck.com/3.1.3/history/3_1_x/version-3.1.3.html"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
