baseurl: ""
full_url: "http://www.rundeck.org"
rd_version: "3.3.2-20200817"
rd_short_version: "3.3.2"

rd_war_name: "rundeck-3.3.2-20200817.war"
rd_war_sha: "2d4edb2f73a4b01283462d8b892fdb31fbfef886"
rd_war_url: "https://download.rundeck.org/war/rundeck-3.3.2-20200817.war"
rd_war_size: "175828581"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.3.2.20200817-1_all.deb"
rd_deb_url: "https://download.rundeck.org/deb/rundeck_3.3.2.20200817-1_all.deb"
rd_deb_sha: "e25a99f5cb83419cf114d0ae94f9f89be54653a6"
rd_deb_size: "176530140"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.3.2"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.3.2"
rd_releasenotes: "https://docs.rundeck.com/docs/history/3_3_x/version-3.3.2.html"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
