baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.11.4"
rd_jar_name: "rundeck-launcher-2.11.4.jar"
rd_jar_sha: "2bdac79aa28938b847266275b807ca031838830d"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.4.jar"
rd_jar_size: "102322692"
rd_deb_name: "rundeck_2.11.4-1-GA_all.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck_2.11.4-1-GA_all.deb"
rd_deb_sha: "d035e96660ebbf179c3b37ec6072e4befc646ccb"
rd_deb_size: "115142132"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.11.4"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.11.4"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.11.4/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
