baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.10.8"
rd_jar_name: "rundeck-launcher-2.10.8.jar"
rd_jar_sha: "0ce13b4473cf2889e7b02cc32b7688b1bf3ab71a"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.10.8.jar"
rd_jar_size: "100342500"
rd_deb_name: "rundeck_2.10.8-1-GA_all.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck_2.10.8-1-GA_all.deb"
rd_deb_sha: "f76b0366920497b8fac787c41296ddeb40a48b3d"
rd_deb_size: "111382826"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.10.8"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.10.8"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.10.8/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
