baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "3.0.3.20180824"

rd_war_name: "rundeck-3.0.3-20180824.war"
rd_war_sha: "d053c6581f623acea4c95321a4cfb0400cee632e"
rd_war_url: "https://download.rundeck.org/jar/rundeck-3.0.3-20180824.war"
rd_war_size: "125525596"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.0.3.20180824-1.201808241856_all.deb"
rd_deb_url: "https://download.rundeck.org/deb/rundeck_3.0.3.20180824-1.201808241856_all.deb"
rd_deb_sha: "57e530aaf7db06a86b292dfcaa7cb6f993b92ccc"
rd_deb_size: "132246252"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.0.3"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.0.3"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v3.0.3/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
