baseurl: ""
full_url: "http://www.rundeck.org"
rd_version: "3.0.19-20190327"

rd_war_name: "rundeck-3.0.19-20190327.war"
rd_war_sha: "c105980112286b0565eefeded9ded7ac1f059b93"
rd_war_url: "https://download.rundeck.org/war/rundeck-3.0.19-20190327.war"
rd_war_size: "147075471"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.0.19.20190327-1.201903272311_all.deb"
rd_deb_url: "https://download.rundeck.org/deb/rundeck_3.0.19.20190327-1.201903272311_all.deb"
rd_deb_sha: "05d5e1eeae3064f03c06b168be1f8070977a7ecb"
rd_deb_size: "158949674"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.0.19"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.0.19"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v3.0.19/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
