baseurl: ""
full_url: "http://www.rundeck.org"
rd_version: "3.0.15-20190222"

rd_war_name: "rundeck-3.0.15-20190222.war"
rd_war_sha: "086b48c6618ae10f9a1aabb40905a8250c802020"
rd_war_url: "https://download.rundeck.org/war/rundeck-3.0.15-20190222.war"
rd_war_size: "141554726"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.0.15.20190222-1.201902230333_all.deb"
rd_deb_url: "https://download.rundeck.org/deb/rundeck_3.0.15.20190222-1.201902230333_all.deb"
rd_deb_sha: "d5a6e5d9b525ea647d9522683087cbe4cb5c4aba"
rd_deb_size: "153383514"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.0.15"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.0.15"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v3.0.15/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
