baseurl: ""
full_url: "http://www.rundeck.org"
rd_version: "3.1.2-20190927"
rd_short_version: "3.1.2"

rd_war_name: "rundeck-3.1.2-20190927.war"
rd_war_sha: "fefedfade477c8722050f22f8328b7cb5bfd6e93"
rd_war_url: "https://download.rundeck.org/war/rundeck-3.1.2-20190927.war"
rd_war_size: "158851429"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.1.2.20190927-1_all.deb"
rd_deb_url: "https://download.rundeck.org/deb/rundeck_3.1.2.20190927-1_all.deb"
rd_deb_sha: "40cbc6b0c529a8d12910f6ee06006e55638f1a60"
rd_deb_size: "172196888"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.1.2"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.1.2"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v3.1.2/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
