baseurl: ""
full_url: "http://www.rundeck.org"
rd_version: "3.0.22-20190512"
rd_short_version: "3.0.22"

rd_war_name: "rundeck-3.0.22-20190512.war"
rd_war_sha: "2625c90b269fbebba3b26b924464dad2d4916ce5"
rd_war_url: "https://download.rundeck.org/war/rundeck-3.0.22-20190512.war"
rd_war_size: "147656807"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.0.22.20190512-1.201905130100_all.deb"
rd_deb_url: "https://download.rundeck.org/deb/rundeck_3.0.22.20190512-1.201905130100_all.deb"
rd_deb_sha: "6ef7cc91b5375d357b50f3097eaeed3562cfa1e8"
rd_deb_size: "159485238"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.0.22"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.0.22"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v3.0.22/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
