baseurl: ""
full_url: "http://www.rundeck.org"
rd_version: "3.3.4-20201007"
rd_short_version: "3.3.4"

rd_war_name: "rundeck-3.3.4-20201007.war"
rd_war_sha: "3cf81c9172a80335b319d1f51ef269df6d1e43cd"
rd_war_url: "https://download.rundeck.org/war/rundeck-3.3.4-20201007.war"
rd_war_size: "169081717"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.3.4.20201007-1_all.deb"
rd_deb_url: "https://download.rundeck.org/deb/rundeck_3.3.4.20201007-1_all.deb"
rd_deb_sha: "2bcf3eb11f7a68f2e0818c9768e022e89db86011"
rd_deb_size: "168259314"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.3.4"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.3.4"
rd_releasenotes: "https://docs.rundeck.com/docs/history/3_3_x/version-3.3.4.html"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
