baseurl: ""
full_url: "http://www.rundeck.org"
rd_version: "3.2.3-20200221"
rd_short_version: "3.2.3"

rd_war_name: "rundeck-3.2.3-20200221.war"
rd_war_sha: "e2e60e3f9f420de1bc91176e009145f2888aa425"
rd_war_url: "https://download.rundeck.org/war/rundeck-3.2.3-20200221.war"
rd_war_size: "164864031"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.2.3.20200221-1_all.deb"
rd_deb_url: "https://download.rundeck.org/deb/rundeck_3.2.3.20200221-1_all.deb"
rd_deb_sha: "55dae22c1ee32e71fc92cf541bf5dbfa6f5133b1"
rd_deb_size: "183860290"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.2.3"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.2.3"
rd_releasenotes: "https://docs.rundeck.com/3.2.3/history/3_2_x/version-3.2.3.html"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
