baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "2.11.1"
rd_jar_name: "rundeck-launcher-2.11.1.jar"
rd_jar_sha: "6a84e1a1480d4e637c83f4120b64b6ff043eb40a"
rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.1.jar"
rd_jar_size: "102309105"
rd_deb_name: "rundeck_2.11.1-1-GA_all.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck_2.11.1-1-GA_all.deb"
rd_deb_sha: "b4821fd0c07428d5a48c49b864f13a7f39e37fdb"
rd_deb_size: "115124992"
rd_zipball: "https://github.com/rundeck/rundeck/zipball/v2.11.1"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v2.11.1"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v2.11.1/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
