baseurl: ""
url: ""
full_url: "http://www.rundeck.org"
rd_version: "3.0.1-20180803"

rd_war_name: "rundeck-3.0.1-20180803.war"
rd_war_sha: "956ba0e88c3d971ed0cc632dfd0380d25aac000b"
rd_war_url: "http://download.rundeck.org/jar/rundeck-3.0.1-20180803.war"
rd_war_size: "127473411"

# rd_jar_name: "rundeck-launcher-2.11.5.jar"
# rd_jar_sha: "a8d2e2de3af66a04bfcd13a59f94629cccb9a3c6"
# rd_jar_url: "http://download.rundeck.org/jar/rundeck-launcher-2.11.5.jar"
# rd_jar_size: "102496072"

rd_deb_name: "rundeck_3.0.1.20180803-1.201808032143_all.deb"
rd_deb_url: "http://download.rundeck.org/deb/rundeck_3.0.1.20180803-1.201808032143_all.deb"
rd_deb_sha: "81af13b9f7c730734077a72711227080f33358a4"
rd_deb_size: "134043946"

rd_zipball: "https://github.com/rundeck/rundeck/zipball/v3.0.1"
rd_tarball: "https://github.com/rundeck/rundeck/tarball/v3.0.1"
rd_releasenotes: "https://github.com/rundeck/rundeck/blob/v3.0.1/RELEASE.md"
markdown: kramdown
gems:
  - jekyll-seo-tag
title: Rundeck.org
description: Rundeck - Job Scheduler and Runbook Automation
url: http://rundeck.org
author: rundeck
twitter:
  username: rundeck
logo: /images/rundeck2-512.png
defaults:
  - scope:
      path: ""
    values:
      image: /images/rundeck2-512.png
